# flake.module.nix — project-specific flake-parts customizations.
#
# seihou does NOT manage this file: it is never regenerated or overwritten by
# `seihou run` or module migrations, so it is the conflict-free home for every
# customization that must survive nix-haskell-flake template upgrades. See
# flake.module.nix.example (generated by the module) for the full option list.
#
# ┌──────────────────────────────────────────────────────────────────────────┐
# │ REQUIRED: this file MUST be git-tracked (`git add flake.module.nix`).      │
# │ Nix flakes evaluate only files tracked by git, so flake.nix's              │
# │ `builtins.pathExists ./flake.module.nix` import guard sees an untracked    │
# │ file as ABSENT and silently ignores everything below — no error, the       │
# │ customization just vanishes from the dev shell. After `git add`, prove it  │
# │ took effect with `nix print-dev-env | grep rdkafka`.                       │
# └──────────────────────────────────────────────────────────────────────────┘
{ ... }:
{
  perSystem = { pkgs, ... }: {
    # librdkafka: the C library hw-kafka-client (and these Streamly bindings)
    # link against. Provides the -dev output (include + lib/pkgconfig) the
    # dev shell needs to build. Relocated here from nix/haskell.nix during the
    # nix-haskell-flake 0.3.0 -> 0.26.0 upgrade so it survives future template
    # upgrades without conflict. (just and process-compose are now provided by
    # the module's own baseDevPackages, so only rdkafka needs to live here.)
    haskellProject.extraDevPackages = [ pkgs.rdkafka ];
  };
}
